#AI Generated code (test run completed, errors corrected)
import pandas as pd
import pprint

def parse_vocations_to_file(excel_file, output_file):
    # 1. Load the spreadsheet
    df = pd.read_excel(excel_file)

    # 2. Ensure 'Job Number' is treated as a string to keep formatting consistent
    df['Job Number'] = df['Job Number'].astype(str)

    # 3. Set 'Job Number' as the dictionary key
    df.set_index('Job Number', inplace=True)

    # 4. Convert the data to a nested dictionary
    vocation_dict = df.to_dict(orient='index')

    # 5. Write the vocation_list.py file
    with open(output_file, 'w', encoding='utf-8') as f: #added UTF-8 encoding to prevent error
        f.write("# This file is auto-generated by build_data.py\n")
        f.write("VOCATIONS = " + pprint.pformat(vocation_dict, indent=4))

    print(f"Success! Created {output_file} with {len(df)} entries.")


# --- EXECUTION ---
if __name__ == "__main__":
    parse_vocations_to_file('Job_Classification_Table.xlsx', 'vocation_list.py')